# Generated by Django 4.2.10 on 2024-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfolder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('yonalish', models.CharField(max_length=60)),
                ('malumot', models.TextField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
